name: TangledMazeLegacy
version: ${project.version}
authors: [mightyone, spthiel, GenerousGuava]
description: ease-to-use maze generator for every shape and every terrain
website: https://www.spigotmc.org/resources/tangled-maze-maze-generator-1-8-1-12.69995/

main: me.gorgeousone.tangledmaze.TangledMain

commands:
  tangledmaze:
    usage: /<command> help
    aliases: [maze, tm]
    default: op

permissions:
  tangledmaze.reload:
    description: Permission for the command /tangledmaze reload.
    default: op

  tangledmaze.build:
    description: Permission for building mazes with a maze wand.
    default: op

  tangledmaze.getwand:
    description: Permission for the command /tangledmaze wand.
    default: op

  tangledmaze.teleport:
    description: Permission for teleporting yourself back to your maze.
    default: op