name: TangledMaze
version: 1.0.0
authors: [GorgeousOne, Spthiel]

main: me.tangledmaze.gorgeousone.main.TangledMain

commands:
  tangledmaze:
    description: Main command for several subcommands wand, select, merge, cut, deselect, start, build.
    aliases: [tm, maze]

permissions:
  tm.build:
    description: Have the ability to build mazes.
  tm.build.vip:
    description: Have the avility to build quiet big mazes.
  tm.build.staff:
    description: Have the ability to build mazes of unlimited size, or whatever is set up in the config.
    default: OP
  tm.getwand:
    description: Be able to get a selection wand by using /tangledmaze wand.
    default: OP