name: TangledMaze
version: 1.2.1
authors: [GorgeousOne]

main: me.gorgeousone.tangledmaze.core.TangledMain

commands:
  tangledmaze:
      usage: /tangledmaze help
      description: 'Main command for all sub-commands: wand, start, select, add, cut, discard, build.'
      aliases: [tm, maze]

permissions:
  tangledmaze.build:
      description: Have the ability to build mazes.
      default: op

  tangledmaze.getwand:
      description: Receive a maze wand with the command /tangledmaze wand.
      default: op

  tangkedmaze.teleport:
      description: Be able to teleport yourself back to your maze.
      default: op