name: TangledMaze
version: 1.2
authors: [GorgeousOne]

main: me.gorgeousone.tangledmaze.core.TangledMain

commands:
  tangledmaze:
    usage: /tangledmaze help
    description: 'Main command for all subcommands: wand, start, select, add, cut, discard, build.'
    aliases: [tm, maze]

permissions:
  tm.build:
    description: Have the ability to build mazes.
        
  tm.mazetp:
    description: Be able to teleport yourself back to your maze,
    default: OP