name: TangledMaze
version: 1.0.0
authors: [GorgeousOne, Spthiel]

main: me.tangledmaze.gorgeousone.main.TangledMain

commands:
  tangledmaze:
    description: Main command for several subcommands wand, select, merge, cut, deselect, start, build.
    aliases: [tm, maze]

permissions:
  tm.build.normal:
    description: Select mazes like a normal person.
  tm.build.vip:
    description: Select extra large mazes like a VIP.
  tm.build.staff:
    description: Select maze of unlimited size or whatever is set in the config.
  tm.getwand:
    description: Be able to get a selection wand by using /tangledmaze wand
    default: OP