name: TangledMaze
version: 1.0.0
authors: [GorgeousOne, Spthiel]

main: me.gorgeousone.tangledmaze.core.TangledMain

commands:
  tangledmaze:
    usage: /tangledmaze help
    description: Main command for several subcommands wand, select, merge, cut, deselect, start, build.
    aliases: [tm, maze]

permissions:
  tm.build:
    description: Have the ability to build mazes.
        
  tm.mazetp:
    description: Be able to teleport yourself back to your maze in case you lost it.
    default: OP